# Generated by Django 5.0.3 on 2024-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="name",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
    ]
