# Generated by Django 5.0.3 on 2024-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_secret_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secret",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
